In [1]:
import numpy as np
import matplotlib.pyplot as plt
import random

1. 

Crear una función que reciba cuatro parámetros: una lista 'L', un número 'T', un número 'V' y un booleano 'S'. La función debe devolver otras dos listas: "lista_train_val" y "lista_test".

- "lista_train_val" es una lista con dos elementos. Cada elemento es una lista: "list_train", que representa el conjunto de entrenamiento y "list_val", que representa el conjunto de validación. 
- "list_test" es el conjunto de test. Como mínimo ha de tener 1 elemento (si 'L' > 1).
- "L" es cualquier lista de elementos. Al principio, entra con un tamaño completo (100%). Esta es la lista que se partirá y se generarán los conjuntos entrenamiento, de validación y de test.
- "T" es un número entre 1 y 100 que va a representar el tamaño, en porcentaje, del conjunto de test "list_test". 
- "V" es un número entre 0 y 100 que va a representar el tamaño, en porcentaje, del conjunto de validación "list_val". Su valor por defecto es 0.
- "S", que por defecto es False, determinará si los conjuntos "list_train", "list_test" y "list_val" son aleatoriamente ordenados. ¿Encuentras alguna posible incoherencia si se reordenan aleatoriamente?

Prueba la función con una lista de 100 elementos números aleatorios del 0 al 100. 


In [3]:
def validation_test(L, T, V=0, S=False):
    lista_train_val = []
    lista_test = []
    L.tolist()

    print("L:", L)
    print("--------")

    if S == True:
        L.sort()
    else:
        random.shuffle(L)

    
    lista_test = L[:int((len(L)+1)*(T/100))]
    no_lista_test = L[int((len(L)+1)*(T/100)):]


    if S == True:
        no_lista_test.sort()
    else:
        random.shuffle(no_lista_test)

    list_val = no_lista_test[:int((len(no_lista_test)+1)*(V/100))]
    list_train = no_lista_test[int((len(no_lista_test)+1)*(V/100)):]
    
    lista_train_val.append(list_val)
    lista_train_val.append(list_train)

    print("length lista test:", len(lista_test))
    print("length lista val:", len(list_val))
    print("length train:", len(list_train))
    print("-------------------------------")

    return lista_train_val, lista_test
    

In [4]:
lista_elementos = np.arange(100)

In [5]:
validation_test(L=lista_elementos, T=80, V=20, S=False)

L: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
--------
length lista test: 80
length lista val: 4
length train: 16
-------------------------------


([array([51, 27, 29, 44]),
  array([31,  8, 65, 40, 76, 55, 48, 72, 94,  4, 26, 67, 79, 82, 74, 83])],
 array([19, 62, 39, 71, 90, 61, 30, 49, 15, 12, 32, 35, 97, 43, 77, 86, 13,
         5, 18, 85,  1, 88, 45, 16, 20, 89, 14, 41, 81, 36, 47, 53, 91, 56,
        59, 78, 70, 98, 93, 60, 23, 92,  6, 68, 37, 80, 11, 99, 21, 75, 46,
        96, 58, 64, 84, 54, 63,  7, 42, 66,  9, 25,  3, 87, 34, 52, 95, 33,
         0, 28, 57,  2, 38, 24, 10, 69, 73, 17, 50, 22]))

2. 

Rehacer el ejercicio anterior en otra función para que no devuelva dos listas, sino los tres conjuntos: 

--> return list_train, list_val, list_test 

In [21]:
def validation_test_v2(L, T, V=0, S=False):
    list_test = []
    list_train = []
    list_val = []

    L.tolist()

    print("L:", L)
    print("--------")

    if S == True:
        L.sort()
    if S == False:
        random.shuffle(L)

    
    list_test = L[:int((len(L)+1)*(T/100))]
    no_list_test = L[int((len(L)+1)*(T/100)):]


    if S == True:
        no_list_test.sort()
    if S == False:
        random.shuffle(no_list_test)

    list_val = no_list_test[:int((len(no_list_test)+1)*(V/100))]
    list_train = no_list_test[int((len(no_list_test)+1)*(V/100)):]
    

    print("length lista test:", len(list_test))
    print("length lista val:", len(list_val))
    print("length train:", len(list_train))
    print("-------------------------------")

    return list_train, list_val, list_test
    

In [22]:
lista_elementos = np.arange(100)

In [23]:
validation_test_v2(L=lista_elementos, T=80, V=20, S=False)

L: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
--------
length lista test: 80
length lista val: 4
length train: 16
-------------------------------


(array([83, 71, 96, 53,  3,  0, 80, 93, 18, 64, 68, 91, 54, 73, 19, 66]),
 array([76, 10, 59, 24]),
 array([ 7,  6, 92, 89, 47, 12, 81, 43,  9, 22,  2, 13, 30, 45, 90, 95, 27,
        85, 35,  4,  5, 98, 38, 99, 84, 23, 69, 86, 48, 57, 70, 46, 34, 28,
        88, 15, 77, 37, 29, 49, 33, 58, 25, 60,  8, 63, 44, 39, 94, 78, 55,
        52, 17, 50, 40, 62, 82, 65, 31, 56, 21, 42, 16, 87, 20, 26, 11, 67,
        74, 97, 79, 41, 61, 75,  1, 14, 32, 72, 36, 51]))