In [3]:
import numpy as np
import matplotlib.pyplot as plt
import random

1. 

Crear una función que reciba cuatro parámetros: una lista 'L', un número 'T', un número 'V' y un booleano 'S'. La función debe devolver otras dos listas: "lista_train_val" y "lista_test".

- "lista_train_val" es una lista con dos elementos. Cada elemento es una lista: "list_train", que representa el conjunto de entrenamiento y "list_val", que representa el conjunto de validación. 
- "list_test" es el conjunto de test. Como mínimo ha de tener 1 elemento (si 'L' > 1).
- "L" es cualquier lista de elementos. Al principio, entra con un tamaño completo (100%). Esta es la lista que se partirá y se generarán los conjuntos entrenamiento, de validación y de test.
- "T" es un número entre 1 y 100 que va a representar el tamaño, en porcentaje, del conjunto de test "list_test". 
- "V" es un número entre 0 y 100 que va a representar el tamaño, en porcentaje, del conjunto de validación "list_val". Su valor por defecto es 0.
- "S", que por defecto es False, determinará si los conjuntos "list_train", "list_test" y "list_val" son aleatoriamente ordenados. ¿Encuentras alguna posible incoherencia si se reordenan aleatoriamente?

Prueba la función con una lista de 100 elementos números aleatorios del 0 al 100. 


In [15]:
def validation_test(L, T, V=0, S=False):
    lista_train_val = []
    lista_test = []
    L.tolist()

    print("L:", L)
    print("--------")

    if S == True:
        L.sort()
    if S == False:
        random.shuffle(L)

    
    lista_test = L[:int((len(L)+1)*(T/100))]
    no_lista_test = L[int((len(L)+1)*(T/100)):]


    if S == True:
        no_lista_test.sort()
    if S == False:
        random.shuffle(no_lista_test)

    list_val = no_lista_test[:int((len(no_lista_test)+1)*(V/100))]
    list_train = no_lista_test[int((len(no_lista_test)+1)*(V/100)):]
    
    lista_train_val.append(list_val)
    lista_train_val.append(list_train)

    print("length lista test:", len(lista_test))
    print("length lista val:", len(list_val))
    print("length train:", len(list_train))
    print("-------------------------------")

    return lista_train_val, lista_test
    

In [16]:
lista_elementos = np.arange(100)

In [18]:
validation_test(L=lista_elementos, T=80, V=20, S=False)

L: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
--------
length lista test: 80
length lista val: 4
length train: 16
-------------------------------


([array([77, 54, 97, 59]),
  array([71, 15, 67, 32, 17, 96, 53, 37,  3, 11, 39, 25, 55,  1, 43, 84])],
 array([51, 16, 14, 27, 99, 98, 72, 76, 47, 58, 29, 36, 73,  8, 12, 74, 57,
        18, 81, 24, 62, 85,  7, 69, 31, 20, 79, 42,  0, 70, 13, 75, 94, 46,
        30,  2, 44, 66, 49, 38, 26, 52, 82, 21, 10, 90, 50, 48, 93, 41, 63,
        22, 65, 87, 64, 40,  9,  5, 88, 89, 19, 56, 23, 86, 60,  6, 83, 28,
        68, 34, 91, 78, 45, 95, 61, 33, 80, 92, 35,  4]))

2. 

Rehacer el ejercicio anterior en otra función para que no devuelva dos listas, sino los tres conjuntos: 

--> return list_train, list_val, list_test 

In [19]:
def validation_test_v2(L, T, V=0, S=False):
    lista_test = []
    lista_train = []
    lista_val = []

    L.tolist()

    print("L:", L)
    print("--------")

    if S == True:
        L.sort()
    if S == False:
        random.shuffle(L)

    
    lista_test = L[:int((len(L)+1)*(T/100))]
    no_lista_test = L[int((len(L)+1)*(T/100)):]


    if S == True:
        no_lista_test.sort()
    if S == False:
        random.shuffle(no_lista_test)

    list_val = no_lista_test[:int((len(no_lista_test)+1)*(V/100))]
    list_train = no_lista_test[int((len(no_lista_test)+1)*(V/100)):]
    

    print("length lista test:", len(lista_test))
    print("length lista val:", len(list_val))
    print("length train:", len(list_train))
    print("-------------------------------")

    return lista_train, list_val, lista_test
    

In [20]:
lista_elementos = np.arange(100)

In [21]:
validation_test_v2(L=lista_elementos, T=80, V=20, S=False)

L: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
--------
length lista test: 80
length lista val: 4
length train: 16
-------------------------------


([],
 array([64, 37, 98, 59]),
 array([36, 58, 35,  2, 74,  4, 53, 46, 61, 19, 84, 16, 15, 63, 52, 55,  3,
        83, 56, 85, 29, 62, 41, 33, 12, 76, 47, 38, 70, 13, 94,  1, 23, 50,
         7,  9,  5, 69, 79, 25, 24, 96, 95, 77, 42, 89, 80, 65, 67, 87, 14,
        44, 21,  0, 54, 49,  8, 48, 99, 30, 93, 28, 97, 57, 51, 31, 86, 71,
        20, 32, 66, 40, 91, 22, 18, 17, 68, 34, 27, 11]))