1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (toca, modifica, prueba) las variables y comenta si hay alguna de ellas que, modificándola, mejore el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [6]:
digits['data'].shape

(1797, 64)

In [8]:
digits['target']

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
np.c_[digits['data'], digits['target']]

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  9.,  0.,  2.],
       ...,
       [ 0.,  0.,  1., ...,  0.,  0.,  8.],
       [ 0.,  0.,  2., ...,  0.,  0.,  9.],
       [ 0.,  0., 10., ...,  1.,  0.,  8.]])

In [9]:
#converting to df
df = pd.DataFrame(data= np.c_[digits['data'], digits['target']],
                     columns= digits['feature_names'] + ['target'])

In [34]:
#removing all digits except 1 and 9.
df = df[(df['target'] == 1) | (df['target'] == 9)]
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
1           0.0        0.0        0.0       12.0       13.0        5.0   
9           0.0        0.0       11.0       12.0        0.0        0.0   
11          0.0        0.0        0.0        0.0       14.0       13.0   
19          0.0        0.0        6.0       14.0        4.0        0.0   
21          0.0        0.0        0.0        2.0       16.0       16.0   
...         ...        ...        ...        ...        ...        ...   
1772        0.0        0.0        5.0       14.0       11.0        8.0   
1774        0.0        0.0        6.0       12.0       12.0        6.0   
1786        0.0        0.0        4.0       14.0       15.0        6.0   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_7  pixel_7_0  \
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
9           0.0        0.0        0.0        2.0  ...        0.0        0.0   
11          1.0        0.0        0.0        0.0  ...        0.0        0.0   
19          0.0        0.0        0.0        0.0  ...        2.0        0.0   
21          2.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1772        0.0        0.0        0.0        4.0  ...        0.0        0.0   
1774        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1786        0.0        0.0        0.0        5.0  ...        0.0        0.0   
1792        0.0        0.0        0.0        1.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        0.0        0.0   

      pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  \
1           0.0        0.0       11.0       16.0       10.0        0.0   
9           0.0        9.0       12.0       13.0        3.0        0.0   
11          0.0        0.0        1.0       13.0       16.0        1.0   
19          0.0        7.0       16.0       16.0       13.0       11.0   
21          0.0        0.0        2.0       12.0       15.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1772        0.0        7.0       15.0       12.0        5.0        0.0   
1774        0.0        2.0       11.0       10.0        4.0        0.0   
1786        0.0        4.0       13.0       15.0        9.0        0.0   
1792        0.0        2.0       14.0       15.0        9.0        0.0   
1795        0.0        5.0       12.0       16.0       12.0        0.0   

      pixel_7_7  target  
1           0.0     1.0  
9           0.0     9.0  
11          0.0     1.0  
19          1.0     9.0  
21          0.0     1.0  
...         ...     ...  
1772        0.0     9.0  
1774        0.0     1.0  
1786        0.0     9.0  
1792        0.0     9.0  
1795        0.0     9.0  

[362 rows x 65 columns]

In [16]:
X = df.loc[:, df.columns != 'target']
y = df['target']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [28]:
#test model
y_predictions = model.predict(x_test)
y_predictions

array([1., 9., 9., 1., 1., 9., 1., 9., 9., 9., 1., 1., 1., 9., 9., 1., 1.,
       1., 9., 1., 9., 9., 1., 1., 9., 1., 1., 9., 9., 9., 9., 9., 1., 9.,
       9., 9., 1., 1., 1., 9., 9., 1., 9., 9., 9., 9., 1., 1., 1., 9., 1.,
       1., 1., 1., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 1., 1.,
       9., 9., 1., 1., 9., 9., 9., 1., 9., 1., 1., 1., 9., 1., 1., 1., 1.,
       1., 9., 1., 9., 1., 1.])

In [25]:
#Score
model.score(X,y)

0.9972375690607734

In [29]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_predictions)
accuracy

0.989010989010989

¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

Yes the score went up from 95% to 99%


LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (toca, modifica, prueba) las variables y comenta si hay alguna de ellas que, modificándola, mejore el porcentaje de acierto del problema.


In [30]:
new_model = LogisticRegression()

In [31]:
from sklearn.model_selection import GridSearchCV

param_grid = [
    {'penalty' : ['l1', '12',  'elasticnet', 'none'],
    'C' : np.logspace(-4, 4, 20),
    'solver' : ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'max_iter' : [100, 1000, 2500, 5000]}
]

clf = GridSearchCV(new_model, param_grid=param_grid, cv=3, n_jobs=-1)

best_clf = clf.fit(X, y)

In [32]:
best_clf.best_estimator_

LogisticRegression(C=545.5594781168514, penalty='l1', solver='liblinear')

In [33]:
best_clf.score(X, y)

1.0